name: 'data_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" to use for this project.
profile: 'data_warehouse'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  data_warehouse:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    
    # Staging models - views for raw data
    staging:
      +materialized: view
    
    # Intermediate models - dimensions and facts
    intermediate:
      dimensions:
        +materialized: table
        +tags: ["dimension"]
      facts:
        +materialized: table
        +tags: ["fact"]
    
    # Mart models - consolidated analytics tables
    marts:
      +materialized: table
      +tags: ["mart"]

