version: 2

models:
  - name: my_first_model
    description: "An example dbt model"
    columns:
      - name: id
        description: "Example ID column"
        tests:
          - not_null
      - name: message
        description: "Example message column"

