{{ config(materialized='view') }}

select
    "Status" as status,
    "TaxAmt" as taxamt,
    "Comment" as comment,
    "DueDate" as duedate,
    "Freight" as freight,
    "rowguid" as rowguid,
    "ShipDate" as shipdate,
    "SubTotal" as subtotal,
    "TotalDue" as totaldue,
    "OrderDate" as orderdate,
    "CustomerID" as customerid,
    "TerritoryID" as territoryid,
    "CreditCardID" as creditcardid,
    "ModifiedDate" as modifieddate,
    "SalesOrderID" as salesorderid,
    "ShipMethodID" as shipmethodid,
    "AccountNumber" as accountnumber,
    "SalesPersonID" as salespersonid,
    "CurrencyRateID" as currencyrateid,
    "RevisionNumber" as revisionnumber,
    "BillToAddressID" as billtoaddressid,
    "OnlineOrderFlag" as onlineorderflag,
    "ShipToAddressID" as shiptoaddressid,
    "SalesOrderNumber" as salesordernumber,
    "PurchaseOrderNumber" as purchaseordernumber,
    "CreditCardApprovalCode" as creditcardapprovalcode
from {{ source('raw_sales', 'SalesOrderHeader') }}
